### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by infacq** [philippK-de/Collabtive#100]
I think this project has similar features to what I need. Is there still support is going on

**Comment by evaK-de** [comment]
Hi there,

yes, it is! We actively develop and support Collabtive and would like to thank you very much for your interest in our software.

If you have any questions regarding the open source core of Collabtive, please have a look at our forums:
http://www.collabtive.o-dyn.de/forum/

It is a place for all kinds of topics related to Collabtive, like bug reports or feature requests.
Many Collabtive users have already posted there issues there. Others have even taken the time to answer questions in detail.

Please use the forum search for your issue. If you don't find an existing applicable subject, just go ahead and create a new thread.

We are looking forward to lively discussions and open talks!

Best regards,

Eva
