### ISSUE TITLE
Fix login/password system to be secure

### ISSUE THREAD

**Issue by yos314** [philippK-de/Collabtive#107]
I just found out from a coworker that he was emailed his password from our instance of this software.  We are running 2.1.1 I believe.

This should NOT be able to happen if the software was using proper security methods for logins.  It should be a salted hash for saving passwords in the database rather than even encrypted passwords.  Forgotten passwords should be deal with by a reset link.  Saving passwords is how you get the leaks that get you on the news.

**Comment by philippK-de** [comment]
Passwords are stored in a hashed format (SHA1).
It is not possible to retrieve the password stored in the database.
However. If a user forgets his password, he can request it to be reset.

To do this, he will have to enter the e-mail address registered for him with the system.
A new password is then generated.
This password is then hashed, and stored in the hashed format in the database.

As a reminder, the user is sent an email with the password that was just generated for him.
You can see the implementation of this here:
https://github.com/philippK-de/Collabtive/blob/master/manageuser.php#L42
https://github.com/philippK-de/Collabtive/blob/master/include/class.user.php#L92

This only works if:
* The user is registered
* Enters the e-mail he is registered with
* The generated password will *only* be sent per email to the registered address and not shown otherwhise.
