### ISSUE TITLE
Need help to fix a bug

### ISSUE THREAD

**Issue by debiruman665** [philippK-de/Collabtive#110]
I'm currently trying to track down why sometimes when I have closed a task and then re-opened it it does not disappear from the timetracker page. 

I had a look in the database and I found the the status of the row has correctly changed so I'm instead trying to look at the template file for the code that renders the timetracker page.

So this code below is from the filtertracker.tpl

`<div class="row">
				<label for="ttask">{#task#}:</label>
				<select name="task[]" id="ttask" multiple>
			  		<option value="">{#chooseone#}</option>
				  	{section name=task loop=$ptasks}
				  		{if $ptasks[task].title != ""}
				  			<option value="{$ptasks[task].ID}" {if $ptasks[task].ID == $task} selected="selected" {/if} >
				  				{$ptasks[task].title}
				  			</option>
				  		{else}
				  			<option value="{$ptasks[task].ID}" {if $ptasks[task].ID == $task} selected="selected" {/if} >
				  				{$ptasks[task].text|truncate:30:"...":true}
				  			</option>
						{/if}
					{/section}
			  	</select>
			</div>`

What I am particularly interested in is wher I can find the code that is executed when this section is run 

`{section name=task loop=$ptasks}`

I want to look at how the page determines which taks to show to find out why the closed taks are still showing on the page.

**Comment by philippK-de** [comment]
The GUI layer of Collabtive has been re-written for the next version of Collabtive. 
This code does not apply anymore, it is from the current 2.2 release.
Please try the current master branch, will will see a public release soon.
