### ISSUE TITLE
there are some errors in js files

### ISSUE THREAD

**Issue by mahsa92** [philippK-de/Collabtive#112]
there are some errors in js files of dashboard in index.php and other parts of project that are shown below 

![screenshot from 2016-08-17 14 25 18](https://cloud.githubusercontent.com/assets/9625844/17732372/956ceba8-6486-11e6-93aa-824ddd9cf671.png)
in addition when i click on cancel button in adding a project i've got this error

![screenshot from 2016-08-17 14 29 43](https://cloud.githubusercontent.com/assets/9625844/17732465/20fee4be-6487-11e6-8b00-b0fbcfdc781c.png)

please help me,thanks.

**Comment by mozhgan-km** [comment]
I have the same problem, please answer soon
thank you

**Comment by philippK-de** [comment]
this is fixed since https://github.com/philippK-de/Collabtive/commit/d23be205ed1c6b5870dc8c6fc6bc4f9e87f7c7ff
