### ISSUE TITLE
please help me, collabtive git plugin

### ISSUE THREAD

**Issue by alamdy** [philippK-de/Collabtive#113]
Hi

please help me, Collabtive + git plugin (integration)
![capture123w](https://cloud.githubusercontent.com/assets/18384264/17892728/71d30cb2-694b-11e6-8e8c-9fb046b86628.jpg)

thanks

**Comment by Vell61** [comment]
There is a plugin?

**Comment by alamdy** [comment]
Pardon, I did not understand?

**Comment by Vell61** [comment]
The problem is what is needed plugin or need to adapt the plug-in?

**Comment by Vell61** [comment]
Ok let's integrate your plugin...
