### ISSUE TITLE
V 3.0 bug List

### ISSUE THREAD

**Issue by PowerChaos** [philippK-de/Collabtive#114]
here are a few bugs in the V3.0

No users online are showing , seems that there are just no users
No Search Bar displayed ( was before this commit )
Only shows my projects in sidebar at Desktop , it does collapse on button press , but it does not show up anywhere else

in user edit => {#tasks#} and {#milestones#} and {#cancel#}

Messages direct -> does not display ThumbNail ( thumb.php )
Messages DropDown ->  does not open lightbox

Progress bar does not fill up ( at 33% but bar is empty ) if you are in the project itself , on Desktop it shows correct

Due date change for projects does not work if you selected No Due date

Time Tracker -> adding value does add hours but doesnt show total hours
Clicking on the collapse button of a time detail does not Collapse
Same counts for messages
This was tested with a single message/Time Tracker 

All testing is done on a Clean install from GitHub with latest commit  07b7523

hope this can help a little :sweat_smile:  

Greets From Powerchaos

**Comment by PowerChaos** [comment]
update , small bug in permitions
if you set a permition group ( new created ) 
then it does not change in database , it even corrupt the database in my case

id  user  role
1	1	1
2	2	2
3	3	2
4	4	2
5	5	3
6	6	2

if i change a seting with the website it all get set on latest user and the role i created the user with ( from 3 to 4 does not work , but from 3 to 1 does work and change all 'user' to user 6 and all roles to 'role' 1

tested on commit https://github.com/philippK-de/Collabtive/commit/0a05db6fae1f2f297253fc10551f6a24097fb4ef

**Comment by philippK-de** [comment]
all of the UI related issues should be fixed by now
i can confirm the roles issue, and will fix asap.

**Comment by philippK-de** [comment]
bug when adding roles is fixed in
https://github.com/philippK-de/Collabtive/commit/cba9668fc1c1a82bbdb347700fb874d99b84db5b
