### ISSUE TITLE
Add GIT management for collabtive (web browser)

### ISSUE THREAD

**Issue by alamdy** [philippK-de/Collabtive#116]
Hi,

I want add  GIT management for collabtive (web browser).

Thanks

**Comment by philippK-de** [comment]
adding GIT support would be a major undertaking. 
i also think it would only be useful for a subset of our users, so probably best done as a plugin

**Comment by alamdy** [comment]
Thank you, Mr philippK-de

Sorry,  where and How ? exactly

**Comment by Vell61** [comment]
Took a turnkey solution and adapted, it get comfortable...
