### ISSUE TITLE
TimeTracker issue still exist

### ISSUE THREAD

**Issue by PowerChaos** [philippK-de/Collabtive#117]
bug still exist from issue #115 

managetimetracker.php?action=showproject&id=5
![timetrack bug](https://cloud.githubusercontent.com/assets/7650333/18957478/8ef12ad2-865f-11e6-8f8d-033b1ce7f279.png)

shows white page if no records exist
tested on commit https://github.com/philippK-de/Collabtive/commit/01ba01083f3814cec0f550216e3c00872bb81085

Greets From PowerChaos

**Comment by philippK-de** [comment]
i cant reproduce this issue.
for me clicking the timetracker tab produces this view: https://i.gyazo.com/65237f9810955cac5292496b328ff10a.png

Maybe you want to try re-installing collabtive completely.
Be aware that 3.0 is a development branch and not meant for production use.
