### ISSUE TITLE
Multi Same user to project

### ISSUE THREAD

**Issue by PowerChaos** [philippK-de/Collabtive#118]
Hi,
this is just a small minor bug
but it is possible to add the same user multiple times to the same project

by doing it that way it shows multiple projects on the homepage 
### project assignment

user1 -> test project
user1 -> test project
user1 -> test project

---
### desktop

desktop user 1 -> 3X test project

---
### admin menu

This could be fixed by removing the user that is assigned from the dropdown list so it can not be selected anymore to add to the same project that it is assigned to

**Comment by philippK-de** [comment]
will investigate
