### ISSUE TITLE
Gantt view

### ISSUE THREAD

**Issue by jeremykraemer** [philippK-de/Collabtive#119]
Hi, do you plan to add a Gantt view ?

**Comment by Vell61** [comment]
I myself have added informative view charts for project and task...

**Comment by philippK-de** [comment]
There is a gantt chart plugin available for Collabtive. 
http://collabtive.o-dyn.de/plugins.php

It has been updated for 3.0 as well.

**Comment by jeremykraemer** [comment]
I didn't have seen the plugin. Thank you
