### ISSUE TITLE
adding a project after edit project does not work

### ISSUE THREAD

**Issue by PowerChaos** [philippK-de/Collabtive#121]
hi,
this is a minor bug

Pressing the add project button opens the form to add a project
but pressing the edit button first will prevent from showing the add project button

reproduce error

Create new project by clicking on Add Project
Click on Edit pencil to edit the fresh created project
Add new project , the edit menu opens again

sidenote
clicking add new project get pre populated by the old value's if you do not reload the page

Greets From PowerChaos

**Comment by philippK-de** [comment]
fixed in 3.1
