### ISSUE TITLE
Total Track Time

### ISSUE THREAD

**Issue by pedrosegolin** [philippK-de/Collabtive#124]
Hello, I found a problem in the system: Total Track Time is not funcionnado is always blank.

![a](https://cloud.githubusercontent.com/assets/14940645/20043829/25140cae-a47a-11e6-8e5d-f2db12c4c3a8.PNG)

**Comment by philippK-de** [comment]
confirmed. to be fixed in 3.0.3

**Comment by philippK-de** [comment]
closed in https://github.com/philippK-de/Collabtive/commit/3d7237b24b6c247326dac5d14bc1bd321bffb8e4
