### ISSUE TITLE
Wrong mail subject

### ISSUE THREAD

**Issue by lodzen** [philippK-de/Collabtive#125]
The subject of the mail looks like **=?utf-8?Q??=** I think its encoded in a wrong way?

**Comment by lodzen** [comment]
I have figured out that the issue is related to the German language.
Changing the following line 121 in "managefile.php" helped to fix the problem partially:
`$themail->send_mail($user["email"], $subject, $mailcontent);`

in

`$themail->send_mail($user["email"], utf8_decode($subject), $mailcontent);`

The subject displays the mentioned text now from the langfile but the special characters like a "-" are not displayed anymore because of the ISO-8859-1 encoding.

**Comment by evaK-de** [comment]
Thanks for the suggestion!
I just replaced the offending character with a simple "-" (minus) in all language files, which should help, too. We'll see if it's still necessary to use utf8_decode in addition.
