### ISSUE TITLE
My system improvements

### ISSUE THREAD

**Issue by Vell61** [philippK-de/Collabtive#129]
I want to show my adaptation to us and I will be happy with your criticism and questions...
http://demo.portal.rnd1.ru
User
demo

**Comment by Vell61** [comment]
I'm ready to share my work and corrections in exchange ... =)

**Comment by Vell61** [comment]
Almost completed the integration with repositories...

**Comment by jdelacruz2712** [comment]
you have many changes, when you raise it?

**Comment by Vell61** [comment]
\demo is raised constantly...

**Comment by azirer** [comment]
Do you have the source code anywhere available?

**Comment by evaK-de** [comment]
As azirer mentioned, we'd need a pull request to be able to include your changes.
