### ISSUE TITLE
No comment for new timetracker entry

### ISSUE THREAD

**Issue by siryan2** [philippK-de/Collabtive#132]
Hello,
thank you for this great Software. I use it very often since many years. 
Since the current update to version 3.1. no comment messages has been stored when creating a new timetracker entry. By looking into the Dev Tools the comment is empty when submitting the form.

Collabtive: 3.1.
PHP: 7.0.26. (shared Hoster, cannout upgrade)

**Comment by siryan2** [comment]
I have noticed that this problem occures when I am using Firefox (latest Version). In Chrome I do not have this issue.

**Comment by philippK-de** [comment]
fixed for 3.2
