### ISSUE TITLE
Install Failure with MySQL

### ISSUE THREAD

**Issue by blackboxgeeks** [philippK-de/Collabtive#142]
When I go to install I keep getting "Requested to use sqlite, which is not enabled!".  I currently have MySQL running on my server and it is used with 3 other web sites so I don't know why it will not install.

**Comment by art83nik** [comment]
1. check permissions (see install doc)
2. edit install.php 
23   $db_driver = "mysql";

**Comment by blackboxgeeks** [comment]
editing the install.php file fixed the problem
thanks
