### ISSUE TITLE
deadlock after closing a milestone

### ISSUE THREAD

**Issue by hardez** [philippK-de/Collabtive#72]
If one performs a "close milestone" 
*/managemilestone.php?action=close&mid=3&id=1*
there is only a blank page with ok. To go back you have to reopen the page.

**Comment by philippK-de** [comment]
I cant reproduce this on HEAD.
You should of course never open this URL directly in your browser.
Instead, it is called via Javascript/xmlhttp when clicking the green arrow next to a milestone.

Works for me.

**Comment by hardez** [comment]
Sorry for not reacting. I never called this site directly, only over the GUI.
