### ISSUE TITLE
Zeiterfassung mit dem neuen Formular

### ISSUE THREAD

**Issue by StephanRichter** [philippK-de/Collabtive#77]
Schritte zur Reproduktion:
Bei einem Projekt auf manageproject.php gehen und die Zeiterfassung aufklappen.
Es wird 8:00 als Start- und 9:00 als Endzeit angegeben.
Man lässt die Stundenzahl bei 1 lässt und ändert Start- und Endzeit händisch.
Dann das Formular absenden.

Erwartetes Ergebnis:
Eingetragene Start- und Endzeit werden erfasst und die Differenzzeit angezeigt.

Tatsächliches Ergebnis:
Als Endzeit wird die Startzeit +1h angegeben.

Weitere Kommentare:
statt 8 und 9 Uhr als vorgabe zu nehmen, wäre es schöner die aktuelle Zeit als Vorgabe zu verwenden. Das war bis zur Änderung so und SEHR handlich!

liebe Grüße,
Stephan

**Comment by philippK-de** [comment]
Die Startzeit auf die aktuelle Zeit setzen: sehr gute idee. werde ich machen (der kunde für den wir dies implementiert haben wollte eben 08:00 als startzeit)

Ich werde wohl auch die "repeat" funktion aus vanilla collabtive entfernen, da ich denke sie ist für viele unklar.

Den beschriebenen Bug kann ich aber in HEAD nicht nachvollziehen.
Wenn ich händisch eingebe:
Start: 06:00 - ende: 12:00 und dann auf abschicken klicke, werden 6h erfasst.
Ausserdem wird auch das "Hours" feld korrekt auf 6h aktualisiert nachdem ich die Endzeit angabe gemacht habe - und bevor ich auf absenden drücke (timetracker::add ignoriert das hours feld übrigens, es arbeitet nur mit start und endzeit/datum)
Firefox/Win7

**Comment by StephanRichter** [comment]
hm, ist irgendwie mit meinem letzten pull-request eh hinfällig
