### ISSUE TITLE
Kundennummer zur Kundenverwaltung hinzufügen

### ISSUE THREAD

**Issue by StephanRichter** [philippK-de/Collabtive#79]
Hey Ho!

Die Kundenverwaltung ist ziemlich neu, und ich bin gespannt, was damit noch alles ermöglicht werden wird. Aber eine Sache ist mir gleich heute beim Betrachten aufgefallen, die ich vermisse: Es wäre cool, wenn man jedem Kunden eine Kundennummer zuweisen könnte, zum Beispiel, damit man einfach nach zugehörigen Datensätzen in anderen Programmen suchen kann.

Oder in meinem Fall: ich fände das superpraktisch für die Open3A-Anbindung.

Stephan

**Comment by evaK-de** [comment]
Sehe ich auch so. Wir merken uns das mal vor!

ENGLISH: I agree with you, that a field for the customer number should be added to the customers, e.g. for easier integration of Collabtive with other software, like e.g. CRM tools.
