### ISSUE TITLE
Installation bricht ohne Warnungen und Fehlermeldungen ab...

### ISSUE THREAD

**Issue by StephanRichter** [philippK-de/Collabtive#87]
...wenn man sqlite nicht aktiviert hat und die config-Datei aus dem Installations-Zip-File unverändert lässt.

Es passiert folgendes: da in der config.php am Anfang kein $db_driver gesetzt ist, wird auf 'mysql' zurückgefallen.
In init.php wird dann aber, wenn $db_name oder $db_user leer sind dann wirder auf sqlite zurückgegriffen. Wenn das aber in der php.ini nicht aktiviert wurde, bricht das Programm ohne Fehler und Warnungen ab. Das kann gerade bei der Installation sehr doof sein.

Ich habe dazu einen Commit gebastelt, der das fixt: https://github.com/StephanRichter/Collabtive/commit/fc12bf345d09533b968359532af76f98fba88833

**Comment by evaK-de** [comment]
Ich kann deine Analyse bestätigen. Selbstverständlich muss nur der Treiber / das Plugin vorhanden sein, das der Benutzer einsetzen will. Deinen Pull Request teste ich, sobald du ihn noch einmal einzeln abschickst, d.h. ohne die vermutlich versehentlich reingerutschten Änderungen, die eine Optimierung der Verfügbarkeitsprüfung des Template-Cache-Ordners darstellen.

Danke, Stephan!

**Comment by StephanRichter** [comment]
ok, habe die beiden Änderungen separiert, und oben den Link korrigiert: https://github.com/StephanRichter/Collabtive/commit/fc12bf345d09533b968359532af76f98fba88833

**Comment by evaK-de** [comment]
Danke für die Anpassung des Commits.

**Comment by StephanRichter** [comment]
Ach so, na dann nehm ich doch die Lorbeeren ;)

**Comment by philippK-de** [comment]
i presume this is resolved.
