### ISSUE TITLE
File Encryption Toggle

### ISSUE THREAD

**Issue by yos314** [philippK-de/Collabtive#92]
Hello.
I've been happily using Collabtive since the beginning of the year, but I have found there is a large limiting factor in its functionality.  The forced encryption has caused some major issues as of late.  

Is there a way to add in a toggle in the config.php that lets you disable this feature?  

The amount of time, ram, and processing power required to decrypt large files is very high.  Though I realize that part of the reason for the forced encryption is because there is no forced authentication system set up to disallow you from downloading files without being logged in. (I am working on fixing my apache config to disallow this)

I will be looking into this for myself also, if I do get it working this way I will attempt a pull request.

Thanks.

**Comment by evaK-de** [comment]
Hi there,

we haven't looked into an option to turn this off. If you would like to investigate this and possible provide a pull requests, we will test it and possibly include it in the repo.

Thx!
