### ISSUE TITLE
update.php broken

### ISSUE THREAD

**Issue by StephanRichter** [philippK-de/Collabtive#99]
Hallo Leute!

Mir ist gerade aufgefallen, das die ganzen Versions-spezifischen Anpassungen in der update.php fehlen.
Habe ich gerade gemerkt, weil bei mir Datenbanktabellen fehlen, die bei einer Neu-Installation angelegt würden. Beim Update wurden diese jedoch nicht berücksichtigt. Ein Beispiel sind die Änderungen in der Company-Tabelle in Commit b8ad3bb1

**Comment by philippK-de** [comment]
Compatibility wird nur innerhalb eines major release beibehalten.
dies gilt auch für update.php
